### ISSUE TITLE
Google image search query change

### ISSUE THREAD

**Issue by nethew** [Sukigu/search-by-image-on-google#10]
Due to a recent change in google image search client=firefox-b-d has to be added in the query. Any client name will do, as long as the client parameter has a value, but seems like firefox-b-d is the standard client name for queries originated from Firefox.

**Comment by es20490446e** [comment]
@Sukigu Are you still maintaining this add-on?

**Comment by BacchusPS** [comment]
I can confirm that nethew's fix worked. Created local copy with the fix, and it worked fine.

Hopefully Sukigu will see this and release an update. If not, Perhaps a fork?

**Comment by es20490446e** [comment]
I'm asking because Sukigu seems to have been absent since 2019:

![Screenshot_20221117_200859](https://user-images.githubusercontent.com/9594332/202536583-a92118b0-f3cc-45fb-906e-af86c31e6be6.png)

No need to fork actually. [Reverse Image Search](https://addons.mozilla.org/en-US/firefox/addon/image-reverse-search/) seems a better alternative right now.

**Comment by Sukigu** [comment]
Thanks everyone for calling my attention to this and for your contributions. 👍🏻 I submitted a new version of the extension and it has just been approved by Mozilla. It should start automatically updating soon.

**Comment by es20490446e** [comment]
Oh thanks 👍

**Comment by nethew** [comment]
Thank you very much for the fix.

**Comment by nethew** [comment]
Also thanks to [grue](https://addons.mozilla.org/en-US/firefox/user/6461203/), the creator of [Contextual Google Image Search](https://addons.mozilla.org/en-US/firefox/addon/conggl/). I found the required parameter in their code.
